### ISSUE TITLE
Other: Switch from shibboleth to AAI-proxy for authentication

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1234]
- [x] AAI-proxy test instance from CSC
- [x] OIDC authentication support against AAI-proxy
  - [x] locally
  - [x] on rems2demo-test (or remsdev?)

**Comment by jaakkocsc** [comment]
CSC's general purpose authentication proxy is up and running at user-auth.csc.fi. It is based on this code: https://github.com/CSCfi/ansible-role-shibboleth-idp-proxy

The proxy supports:
* SAML2
* OpenID Connect
Supported authentication methods
* Haka
* Virtu
* suomi.fi
* Social media 
* Basically any SAML2supporting identity provider can be integrated as an authentication method
Features:
* Pass through attributes and claims from authentication sources to services
* Transform attributes and claims from authentication sources to services
* Query additional data sources for additional attributes and claims
    * Requires data source with appropriate user information 
* Services can request specific authentication method in authentication request

**Comment by hukka** [comment]
After #1699 and related deploy merges are done, we are using OIDC on remsdev. After that it's a matter of getting production configs and enabling them on other instances.

**Comment by mmatthiesencsc** [comment]
Note that CSC AAI for LBR only works if CSC AAI supports eduGAIN and the CLARIN IdP. I am just in discussions about this. CLARIN support looks promising.
LBR is here a slightly special case since we have to support the CLARIN IdP to be recognized members of CLARIN.
For the next update we should have a proper staging environment that uses production login to be able to test this properly.
