### ISSUE TITLE
need clarification around dynamic workflows and workflow templates in the demo site

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1254]
Dear REMs team,

Apologise if I got the concept around workflows wrong. We have been testing REMs for a few months now and need some clarification about how to create new workflows.

We realised from previous versions that users were able to create/edit new rounds when creating new workflows.
However, in the current demo version the only workflow available is "dynamic" and we can't see the option to add different rounds like for example the one already created called "two rounds".

My question is:

- What dynamic workflows means and how they work?
- Is it possible to define the rounds for a workflow? how?

thank you very much

**Comment by opqdonut** [comment]
Yeah the workflow concept has changed. We'll document the changes in the release notes of the next release (should be out soon...).

Quick summary:
- it turns out the strict structure of a round-based workflow wasn't a good fit for some organizations, and that nobody really needed all the features of the round-based workflow
- we implemented a new dynamic workflow, and to simplify the code, deprecated the old round-based workflow
- a dynamic workflow has one or more users as _handlers_ who are responsible for guiding the application through the process. The handlers can request comments and decisions from other users, return the application to the applicant, add licenses, change members, etc.
- it is possible to add new workflows to REMS, and we'll probably add at least an autoapprove workflow
