### ISSUE TITLE
Let user set the language of the emails they receive (LBR)

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1371]

**Comment by okahilak** [comment]
From LBR: "We think choosing the email language according to which language the user (be it applicant, approver or administrator) has user in the interface would make the most sense (and should be relatively easy to implement)."

**Comment by UFOPOLI** [comment]
There's a typo in my original comment. Should be "had **used** in the interface".

An additional clarification: tying the email language to the interface language also makes more sense than having some kind of user settings that the user would have to actively modify (very few would do that). In other words, this would work so that, Finnish being the default language, those users that have switched the interface language to English would receive English mails, others Finnish.

**Comment by mmatthiesencsc** [comment]
I also think the browser language should suffice. Should a user later change the browser language and apply in that language it is fair to assume he will be able to read the resulting mail that matches the browser language.

**Comment by UFOPOLI** [comment]
By "browser language", do you mean the language the user's browser software operates in? Because I mean the choice they have made in the LBR interface (FI/EN).

**Comment by mmatthiesencsc** [comment]
I meant the same thing. I should have said user interface language.
