### ISSUE TITLE
LBR new production entitlements end problem

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#1372]
Entitlements have gotten end date to the migration date 14.6.2019

**Comment by okahilak** [comment]
Here is the command that we ran to get the SQL commands to fix the issue:

```(def apps (rems.db.applications/get-all-unrestricted-applications))
(def apps' (filter #(and (not (rems.application-util/accepted-licenses? % (:application/applicant %)))
                         (= :application.state/approved (:application/state %)))
                   apps))

(defn application-to-sql-command [app]
  (let [id (:application/id app)
        events (rems.db.events/get-application-events (:application/id app))
        licenses (map #(into {} [[:license/id %]]) (first (vals (:application/accepted-licenses app))))
        new-event (assoc (first (filter #(= (:event/type %) :application.event/created) events)) :application/licenses licenses)
        in-json (rems.db.events/event->json new-event)
        cmd (str "UPDATE application_event SET eventdata = '" in-json "'::jsonb WHERE id = " (:event/id new-event) ";")]
    cmd))

(def cmds (map application-to-sql-command apps'))
(doseq [cmd cmds]
  (println cmd))```

We additionally ran:

```DELETE FROM resource_licenses WHERE endt IS NOT NULL;

UPDATE entitlement SET endt=null where endt > '2019-06-14 10:00:00' and endt < '2019-06-14 11:00:00';```

**Comment by hukka** [comment]
Postmortem follows.

Original actions
============
Old instance of REMS was updated using the `lein run migrate`, creating a new dynamic workflow and `lein run convert-to-dynamic <workflow id>`. The server was running during the migration, and the tomcat was restarted afterwards.

Problem
=======
Significant portion of entitlements were closed, and users lost access to the resource databases. The entitlement API checks the `endt` column of the entitlement table. A large number of rows in the DB had the end datetime set to the time the migration ran, within a timespan of roughly a minute.

Mitigation
=======
AAI middlepoint in the stack was hacked to ignore entitlement ending dates from a given range.

Analysis
=======
The entitlements are granted (created) and revoked (endtime set) by the entitlement poller. The poller had noticed that the affected users didn't have proper access rights. Disregarding bugs, this would mean that the applications are not in approved state, the users are not part of the application, or haven't accepted licenses. The reason for the design is that applications could be approved *conditionally*, with entitlements being automatically granted when the users accept licenses (either original, or any added licenses). Similarly if a user is removed from the application (possibly because they depart from their research group), the entitlements will be automatically revoked.

The conversion from old workflows basically recreates the events within the new workflow. My first theory was that because the server, and thus the poller, was running in the background while the conversion was done, it would see applications while they have been created, but not yet approved – before all events for that application had been saved. Normally the poller should then grant new entitlements when new events are created, but I suspected that caching is interfering with the system, since the SQL DB was changed without the server being aware of any changes.

This was falsified by running the conversion again locally from a saved DB dump, without the server: when the server was finally started, it immediately went to revoke the entitlements.

Deeper analysis of a random sample revealed that the problem is that the applications have different required licenses than what the users have historically approved. Some were missing, some were extra. When the conversion creates the new events, it checks the DB for all licenses that are related to either the resources, or the workflow. The missing licenses were related to workflows: originally the applications were part of a workflow that had a license, but the new dynamic workflow didn't have any. The extra licenses were such that *at some point* they were attached to the resource, but *not at the moment the applications had been originally created*. At first it seemed like problem was related to revoked license links (that is, the licenses do exist and do not have a end time, but the link to the resource did have an end time that was earlier than the application's creation). Later, we found out that in some cases there were also licenses that were linked to the resources after the applications had been made.

The conversion logic uses the same functions to create applications, as the main code. The main code assumes that everything is happening right this moment, but also that resources and their linked licenses are immutable: if licenses would change, also a new catalogue item would be created. Current REMS does not allow changing the catalogue items like this in place, does not allow setting end times, and does not check for them properly. Historically this had been used to replace licenses with others.

This does affect also new applications, made with new REMS UI, when applying those same resources: the new REMS requires the users to accept every single license ever historically linked to the resource. However, it would have not made it impossible to apply, or get entitlements, nor would the entitlements have been revoked at a later point (since the users would have accepted too many, not too few licenses).

Last, we found that in five cases there were new entitlements being granted, since the system could not see any reason not to.

Solution (for this instance)
====================
We checked all the licenses that were involved in this matter. Significant portion was license called "I understand that I need an <customer> account". Others were clarifications or typo fixes. So no actual problems of users not having accepted crucial licenses was found.

We modified all entitlements that had an endtime during the migration by removing the endtime (setting to null). This allows the entitlements to be enabled again, even without the hack on the AAI layer.

Then we we modified the new converted created events directly in the DB so that the required licenses matches what the users have accepted. Thus the record of what has been done by the users stays invariant and can be verified later. This makes sure that the poller will not revoke the entitlements again later (if and when they get new events, such as having members removed).

Alternative would have been to create new license accept events, but even with simple typo fixes, this was deemed to damage the trust in the integrity of the data on how users have interacted with the system.

Finally we deleted all expired resource license links from the database, so that new applications wouldn't have too many licenses to accept.

After the fixes four more additional licenses were created, to total of nine. The hypothesis for the extra granted licenses was that since the original workflow had an explicit and manual step of giving entitlements, they were not given in every case if the user actually already had access to the data due to accidental multiple applications or if the data was in fact available via institutions. Thus these extra entitlements were left as is.

Open issues
==========
This will happen again, if the conversion is ran again on a database that has history of having revoked license links.

The problem stems from the mismatch of if the links can be modified in place at all (old REMS could, new cannot) and the logic where entitlements are not part of approval, but can happen automatically at a later point. Both customers have indicated that such functionality is not required, and in fact might be undesirable. While this is true for just the first applicant, there needs to be a question of whether any added members to the application should be handled automatically or will/can they also go through another manual approval.

**Comment by mmatthiesencsc** [comment]
I did not quite understand "The problem stems from the mismatch of if the links can be modified in place at all (old REMS could, new cannot) and the logic where entitlements are not part of approval, but can happen automatically at a later point. Both customers have indicated that such functionality is not required, and in fact might be undesirable." Did you mean "licenses are not part of approval"? In any case, being picky about not be able to change links is futile, since we use PIDs (URNs) where the very point is that they can be changed. We are careful when changing license pages, but REMS has limited options to make sure that the license page is unchanged from one point in time to the next.

**Comment by hukka** [comment]
I meant that entitlements are not part of the approval, that is, before it was a separate manual step, and now it is separate step done automatically. If every approval could be interpreted as granting an entitlement, the related business logic would have been simpler.

And the comment on immutability of the new REMS is part of the technical explanation; the legacy, migrated data has cases that are impossible to generate with the current UI, so there are gaps when that old style data is not interpreted correctly. In this case, changing licenses on a resource is not possible like before, but a new resource would have to be created and old disabled.

**Comment by mmatthiesencsc** [comment]
Hi Tomi, ok, now I get it. Invitations imply that the PI can add/remove entitled users at will. That might be ok in most cases, but some resource owner might want to reserve that power to themselves. Actually I just realised that ANY applicant can add ANY number of members to approved applications? That should be prevented as soon as possible.

License changes indeed are rare and handling them via disable/enable is perfectly ok. At least with the links we have the option to fix typos without having to disable/enable resources.

**Comment by hukka** [comment]
Sorry for the confusion. Applicants can only remove or uninvite members. Only handlers can add members (if the users are already in the system) or invite members (via email). The relevant case here would be if the handler wants somehow to verify who the user is in the authentication system, and not rely on email.

Of course this could be worked around by simply asking all the future users to log in to rems once, so that their information becomes available, and the handler can then add them.

**Comment by mmatthiesencsc** [comment]
Hi Tomi, ok, no problem. My double role here confused me. An option to vouch for a user could be an "application" that does not really apply for a resource, but that makes it possible to request a comment from an external party to vouch that the user is who he claims to be. This could be implemented in the present system. I agree that email alone is too weak for verification purposes. But I veer off topic...
