### ISSUE TITLE
Show enabled/archived status and buttons when viewing an individual entity

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1438]
Currently it's confusing when viewing a catalogue item right after creating it and it says that it's active, but actually it's disabled. All entities which have a page in the admin pages should have that information and buttons when viewing a single entity, in addition to the buttons on the listing page.

**Comment by okahilak** [comment]
Added enable/archive buttons to all 'View' pages (that is, catalogue item, license, resource, form, workflow), and changed the definition of 'Active' so that a disabled item is not active.

This seems to give enough information to the user to be able to infer that a newly-created catalogue item is not in use, so I'll close the issue.
