### ISSUE TITLE
Scrolling to top of page after modal closes

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1477]
was implemented originally in #1337 (see also #1435) but is now broken

**Comment by okahilak** [comment]
I commented already on the pull request, but: I think it's not an improvement if the page automatically scrolls to top when doing, e.g., either of these two actions:

- Accepting terms of use
- Inviting a member to an application

What I would expect the page to do is to remain at the same location and indicate that the action was successful by the change on the page content, e.g., in the former case, by "Accepted terms of use" text appearing on the page. If the page scrolls to the top, the workflow of the user is cut short until they scroll back to where they were on the page.

**Comment by luontola** [comment]
For screen readers the current behaviour is broken - the focus is in an undefined place when the modal dialog is closed. PR #1478 will at least make it usable. It's another issue that the modal dialog is a bad design for many situations where it's currently being used.

**Comment by okahilak** [comment]
Right, so it seems that fixing this issue improves things in some ways, while in some other ways, I think the usability becomes at least somewhat worse.

I assume that the aspects in which usability becomes worse are fixable by some further tweaks to the pop-ups, so I guess fixing this issue is a step to that direction.
