### ISSUE TITLE
Re-implement auto-approve application workflow

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1494]
At least NKR has a use case in which they need this feature.

**Comment by okahilak** [comment]
In short, this is a workflow in which the application is automatically approved if the user submits an application and has the terms of use accepted.

As I understand, this feature existed before but was gone when workflows other than dynamic workflow were removed.

**Comment by okahilak** [comment]
A remark from NKR: It is important that even though the permission is automatically granted in auto-approve workflow, there has to be a named approver/handler who can later remove the permission if needed.

**Comment by opqdonut** [comment]
After a bit of discussion, it sounds like there needs to be some logic that looks at the applicant and then decides to autoapprove. Autoapprove can't be a separate workflow since an application might either get autoapproved or handled normally. So we'll probably implement an option in the dynamic workflow.

Needs more information.

**Comment by okahilak** [comment]
Duplicate of https://github.com/CSCfi/rems/issues/1509
