### ISSUE TITLE
Automatic handling of entitlements when application is copied

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#1506]
When an application is renewed by copying it as a new application, there could be automatic handling of entitlements. Eg.
    * Find out when to remove old entitlements (when copied as a draft, submitted, approved, when handler closes the old application)
    * What happends to old entitlements if new application is rejected?

**Comment by Macroz** [comment]
I guess automation is rather difficult with this little information. For example:
- If the access right expires, there could be a date set for entitlement expiration already, and it works.
- If the old application is closed, and then a new application is made, the entitlements will be handled correctly.
- The old application could still be valid after the new linked application is approved or rejected. I think it depends on the case of the handling organization.

Since we don't have much to go with I'll close this issue and we'll open a new one / reopen when a clear use case appears.
