### ISSUE TITLE
API Key Limits

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#1662]
There is a need to limit what API users can do. I.e. now API key can represent any user and do any operation that is allowed for that user. There should be a possibility to limit the user, role or API function that can be used.

- [ ] API key class that can only create/close applications i.e. applicant role only
- [ ] API key for readonly entitlements

**Comment by opqdonut** [comment]
Implementation ideas:
- External HTTP-level firewall (e.g. disallow everything except /application/create) when x-rems-api-key header is present
- Internal HTTP-level firewall: list allowed endpoints per api key
- Associate api keys with roles. "This api key can only impersonate users with this role" or "This api key can only perform commands with this role"

**Comment by okahilak** [comment]
We decided to try roughly the following approach:

- Have a list of roles associated to each API key, determining which roles are allowed for that API key.
- If a user logs in who has roles not allowed to be used with the API key, drop those roles from the list of roles for that user and that session.
(- If a user attempts to do an action that is not allowed due to the restrictions set by the API key, have an error message indicate that.)
