### ISSUE TITLE
Why are organizations a server config?

### ISSUE THREAD

**Issue by sherzinger** [CSCfi/rems#2124]
Hi,

not sure if this is intentional. If it isn't please consider this a feature request.

Why are organizations a file configuration option and cannot be configured in the UI by `owner`?

Another (minor) thing I noticed is that organization columns are present in multiple tables but not linked. So there is no easy way of removing or editing an organization, but one most go in each table separately.

Kind regards,
Sascha

**Comment by opqdonut** [comment]
The organizations feature is being reworked currently, see #2039 #2035. Soon the organizations will be in the database instead of the config file.

We imagine that most users of REMS won't need organizations, and can just stick with one `default` organization.

The point of the organizations feature is to allow delegating the administration of some resources managed by REMS. However, we're also working on a feature where a review can be assigned to an organization (see e.g. #2041).

Hope this helps...

**Comment by sherzinger** [comment]
Okay, that's good to hear!

Regarding #2039 : I assume those CRUD operations will be exposed via API?

**Comment by opqdonut** [comment]
Yes

**Comment by sherzinger** [comment]
Okay, then this issue a duplicate :-) 
Thank you!

**Comment by Macroz** [comment]
While I'm working on these, if you have some specific requests for what you need, then let me know here or in another issue. I can comment on, if they will be possible, or tune the code perhaps to make them possible. We have some specific use cases that we are aiming for, but small changes are often easy.

**Comment by sherzinger** [comment]
Thanks @Macroz !
I'll let me colleagues know.
