### ISSUE TITLE
Owner cannot accept application invites

### ISSUE THREAD

**Issue by sherzinger** [CSCfi/rems#2243]
Hello,

we've stumbled over an issue where we get the error below when trying to accept an invitation.
We tried to send an invite to a new user and it worked without issue. However, when sending an invite to an "owner" they cannot accept it. We also tried a private browser session, to make sure it's not cache related.

In the default `en.edn` there also seems to be a `:forbidden` translation missing.

![Screenshot 2020-06-30 at 08 58 26](https://user-images.githubusercontent.com/11333940/86096977-53247800-bab4-11ea-80f2-11d765646553.png)

**Comment by Macroz** [comment]
Hi and thanks for the report,

I think we recently ran into the same case where testing was done with "super users" and not normal users. It's impossible for someone who already a role in an application (i.e. applicant, or handler) to accept an invitation. You can see `accept-invitation` is only available for the `everyone-else` role. Handlers already have the handler role for example. A pure owner that is not a handler can accept an invitation. Because this is not a problem that is relevant for real production use so, we are unlikely to fix it at the moment.

You can see all the available actions here https://github.com/CSCfi/rems/blob/master/docs/application-permissions.md

**Comment by sherzinger** [comment]
Yes that was it indeed. The owner in this case was the handler of the application he was invited to (totally missed that).

**Comment by Macroz** [comment]
Good, perhaps we can close this issue?

**Comment by sherzinger** [comment]
Sure!
