### ISSUE TITLE
URL should not be discarded when user is not logged in

### ISSUE THREAD

**Issue by sherzinger** [CSCfi/rems#2247]
Hello there,

When an user it not logged in and opens a link (e.g. https://rems.foo.com/application/58) they will be redirected to the login page and the original url is completely ignored, even after successfully logging in. It would be nice if the login logic could take the original target into account.

Reason: It's quite cumbersome for a user to click on a link somewhere, log in, and then get greeted with a page completely unrelated to the clicked link.

**Comment by Macroz** [comment]
After login you are redirected back to the original page. So this should just work (with some usual caveats). Can you provide more detailed steps on how you encounter this?

**Comment by sherzinger** [comment]
Hi Marcoz,

nothing special actually:

1. Go to https://rems.lcsb.uni.lu/application/58 
2. URL changes to to https://rems.lcsb.uni.lu/ 
3. I login
4. URL changes to https://rems.lcsb.uni.lu/catalogue (I'd expect to be the URL from 1.)

**Comment by Macroz** [comment]
Does the user you use for login have the rights to see that application?

**Comment by sherzinger** [comment]
Absolutely, when I use the link in 1. after logging in I end up exactly where I want to be.

**Comment by Macroz** [comment]
Ok I will try to reproduce, this is not how it is intended to work.

**Comment by sherzinger** [comment]
Thank you!
I also had a quick look, just in case I configured nginx wrongly, but this looks correct to me:

```
        location / {
            proxy_pass http://127.0.0.1:3000;
        }
```

**Comment by Macroz** [comment]
I'm unable to replicate this. 

If I open an incognito browser, type url e.g. `http://localhost:3000/application/9`, then do the login, I get redirected to the correct application provided I have the rights (if I don't I get the forbidden page).

The relevant browser logs are
- `Received unauthorized from http://localhost:3000/application/9` (initial page is forbidden because not logged in, this is stored)
- `Navigated to http://localhost:3000/` (login page is currently the main page where you can select from potentially several login services)
- `Navigated to http://localhost:3000/fake-login` (only appears if dev fake login, this should be the actual login service)
- `Navigated to http://localhost:3000/redirect` (URL where the login service should redirect you after successful login)
- `Redirecting to http://localhost:3000/application/9 after authorization` (redirect page has noticed that you were going somewhere before)
- `Navigated to http://localhost:3000/application/9` (desired URL)

The redirect phase must be going wrong for you as it does the regular front page redirection depending on user role. The url is stored in the browser session storage while the user is in the login service. After the successful login you should direct the user to `/redirect` for it to work. I'm guessing but perhaps this second part is not correctly set up in your deployment and you direct elsewhere.

**Comment by sherzinger** [comment]
hey @Macroz,

thank you very much for the testing and explanation.
Can you tell me where I would setup this redirect?

In Auth0 I've this callback URL whitelisted https://rems.lcsb.uni.lu/oidc-callback
Nginx is doesn't have any rules other than the one above.

Are you saying I need to setup manually redirect rule like this?
https://auth0.com/docs/rules/guides/redirect

**Comment by Macroz** [comment]
I think your configuration is like it is supposed to be for OIDC. There may be a bug in the OIDC implementation or SPA that breaks it for you and my recollection is about how I originally implemented it pre-OIDC. We'll have to check it later.

**Comment by sherzinger** [comment]
Thank you!
If you need any help testing please let me know.

(I did already test it with a private browser session to rule out a broken session storage.)

**Comment by opqdonut** [comment]
Reproducible on at least with remsdev.kaj.pouta.csc.fi
