### ISSUE TITLE
DUO compatibility check

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2315]
When an application has a DUO field and the resource has DUO codes, check if the codes of the application match the codes of the resource.

"Thumbs up for the handler"

- [ ] associate a set of DUO codes with resources when creating resource
- [ ] show DUO code compatibility when viewing application: for each DUO code in the application, show a check mark if it's in the resource, cross if not (compare licenses)

**Comment by opqdonut** [comment]
split out from #776

**Comment by Macroz** [comment]
Here's some discussion about the exact implementation. 

- We can fetch the latest DUO codes from https://github.com/EBISPOT/DUO/blob/master/duo.csv or with releases https://github.com/EBISPOT/DUO/releases. We can automatically fetch them and we should probably try downloading new codes every day.
- DUO codes are essentially immuitable so that there should not be great differences to the wordings of the texts for a given ID. They are as a group versioned by the dates. 
- It's an open question how to localize the codes, or if it's even possible. For this to work out for a dynamically fetched dataset, we need to build the localization as a feature of the UI.
- We should consider if we should flag the changed wording, at least in the automatic compatibility check.
- We should also consider how to make it easy to upgrade to the later versions for the dataset owners. Although the meaning of the DUO code should not change they may in practice disagree with the new wording.

These considerations also apply to #2314

**Comment by Macroz** [comment]
We have now implemented DUO as an experimental feature, a little bit different than in the task here (since we learned new things). Further tasks in #2763.
