### ISSUE TITLE
can't save a form

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#668]
** CHANGE REQUEST ***
severity: high

Dear REMS team,

I am testing v2.3 and realised the new aministration option to create forms but the "SAVE" button is always disabled.

could this be fixed so user can save new forms?

thank you

**Comment by luontola** [comment]
I'm confused because [v2.3 doesn't even have the page for creating forms](https://github.com/CSCfi/rems/blob/v2.3/src/cljs/rems/administration.cljs#L139-L142). Probably you are running an incomplete development version between v2.3 and the current master. Try updating to the latest master - the feature is implemented there.
