### ISSUE TITLE
LBR migration found issues

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#989]
This is an issue that collects all the issues that have been noticed in the LBR migration to the new dynamic application model.

- Disabled items warning (see https://github.com/CSCfi/rems/issues/1002)

**Comment by mmatthiesencsc** [comment]
From Tero Aalto:
Some observations:

The page title is wrong. It says "Welcome to REMS" (in both languages) while it should be "Kielipankin oikeudet" and "Language Bank Rights".

Speaking of which, Finnish should be the default language. The active language should be highlighted in the menu.

The tab "Aineistoluettelo" should be "Kielivarat".

The catalogue should be in alphabetical order.

It seems that the application numbers have changed from simple running numbers to year/number. This may be more human-readable now, but it may also make it difficult to refer to past applications by number (for example by external parties who have received application data in pdf format from us).

Is this version supposed to contain all past data? At least in the "Käsitellyt hakemukset" table, there's only one at the moment. Also, "Processed applications" might be a better English translation than "Handled".

The Administration page has two different navigations with identical function. The front page doesn't seem to have any function and could be removed.

The blue font in the Catalogue items table of the Administration section is not in our palette, and not very readable. The rightmost buttons are slightly cut on the edge (at least on my screen).

The font looks different, but that may be my VM's fault. In any case, perhaps the main menu was cleared when the items were in all caps?

**Comment by mmatthiesencsc** [comment]
The GUI is slow. It takes 15 seconds to show the Catalogue every time.
To repeat:

Click About
Click Catalogue
Wait 15 secs before it appears.
Click About
Click Catalogue
Wait again 15 seconds.
(repeat)

Tested on the newest Chrome in Linux.

**Comment by mmatthiesencsc** [comment]
Workflows: Only the Dynamic one is shown all others seem to never show and create a 500 error in the JS console: e.g. https://lbr.csc.fi/api/workflows/33

**Comment by mmatthiesencsc** [comment]
"Actions" seem to be equally slow (15 secs.) I tested also on Firefox ESR, Chrome is not to blame.

**Comment by opqdonut** [comment]
FYI, we're currently doing performance testing & optimization (#863). Improvements should soon be available.

**Comment by mmatthiesencsc** [comment]
"Invite Member" using Name and Email does not seem to work.  Maybe only known users can be added, but that should be stated in the GUI. We might also later decide we would not want this feature for LBR.

> FYI, we're currently doing performance testing & optimization (#863). Improvements should soon be available.

Good to know, thanks! The issue seems to be in all more dynamic menu items.

**Comment by mmatthiesencsc** [comment]
I got no emails during the application process. This might be deliberate or a bug.

**Comment by opqdonut** [comment]
I'm pretty sure email sending is disabled in your preproduction environment.

**Comment by mmatthiesencsc** [comment]
Here's a summary of Tero's and my meeting about LBR.

In general we were very happy with the changes and the added functionality!

I am sure that some issues can be fixed by ourselves (e.g. by changing the localisation files, but I decided to list them all here.

We also got the feeling that some of the GUI items we critizied below were requested by THL?

Version: v2.4-2074-gb6801ffc (wrong blue)

General

The font should be LATO.

Language selector:
 - CAPS missing
 - wrong blue
 - active language should be orange

Typo: Sign Out > Sign out

Continue Existing Application > Continue existing application
Apply for Resources > Apply for resources

Grey buttons: Make them blue (lighter than headings) [Tero: check colours]

Check colour scheme: https://www.kielipankki.fi/organization/media/
Terms of Use licence links also have wrong blue.

All "Success" popups seem superfluous. (we could not find one of those popups that made sense to us.)

Menus:

* Actions

"Description"

Wrong heading: Change to "Application/Hakemus"
Show application number as before

Handled applications:

Tero has different view compared to Martin (1 application vs. a lot).

Show less / Show more: wrong blue.


* Catalogue

"Accept terms of use Success"-popup could be removed.

- Applicants:

Accepted terms of use [] -line could be removed (has own heading).

"Remove member ..." / "Invite Member ...": remove dots.

Invite function is unclear, what should happen?

Remove "Save as draft" (not needed in LBR)

"Send application Success" popup: check white edges. The whole popup could be removed.

"Abstract of Research Plan or Short Summary of Purpose of Use (optional)"
-> make compulsory.

Potential bugs:

Returned application allows to add members. If you don't choose a member and press Add member you get a 400 error.

To repeat:

Apply
Return application
Click Add member
-> Failed 400 (400) OK

Choose Member also fails:
Select a person
Click Add member
-> Failed Missing translation [:forbidden]

(The whole function should not be available to end users)

* Administration / Licenses

[x] Active does not change
Archived License can be enabled but remain archived?

**Comment by mmatthiesencsc** [comment]
A short summary of issues, one per line:

* GUI look
- Title wrong
- Language not in sync with browser default
- GUI strings need change
- Catalog not ordered by default
- Colour scheme inconsistent
- Font need checking
- Admin page menu twice
- Remove in LBR: Success popups, Invite Member, Save as Draft 

* Functionality
- Inconsistent views of admins (Martin/Tero see different things in admin GUI)
- GUI slow
- Enable email sending (for testing)

* Clear bugs:
 - Return Application > Add Member
 - Administration / Licences

**Comment by foxlynx** [comment]
Performance issues fixed in #863

**Comment by foxlynx** [comment]
Layout, translation and color fixes: #1128

**Comment by foxlynx** [comment]
Email sending for testing purposes: #1129

**Comment by foxlynx** [comment]
The catalogue should be in alphabetical order: #1130

**Comment by foxlynx** [comment]
Different font for different REMS instances: #1132

**Comment by foxlynx** [comment]
Different application numbering for different REMS instances: #1133

**Comment by foxlynx** [comment]
Invite member bug: #1134

**Comment by foxlynx** [comment]
Non-dynamic workflow bug fix: #1135

**Comment by foxlynx** [comment]
> * Remove in LBR: Success popups, Invite Member, Save as Draft
> 
Success popups and Save as draft not to be removed at the moment. Maybe later when the product is more mature?

**Comment by foxlynx** [comment]
> Tero has different view compared to Martin (1 application vs. a lot).

This was due to Tero not being created as a handler for the new, dynamic workflow. This is now fixed. Also found a bug from logic, see #1143

**Comment by mmatthiesencsc** [comment]
> > * Remove in LBR: Success popups, Invite Member, Save as Draft
> Success popups and Save as draft not to be removed at the moment. Maybe later when the product is more mature?

We can live with the success popups. Save as Draft was configurable in our present version (it is not there), has this behaviour changed? If it is easy to remove then please do.

Invite members is a potential security risk at the moment, if ordinary users can "invite" users that have logged in before from a list. (I am not sure whether I could because of my admin status). The option is also confusing, since users will likely "invite" other users with emails unknown to Haka. Please remove this option for now, since it creates more usability problems for us than it solves.
